---
    - name: install python, python tools, nginx
      apt: name={{ item }}
      with_items:
        - python3.6
        - python3-pip
        - build-essential
        - python-dev
        - nginx

    - name: install python dependencies and addtl modules
      pip: name={{ item }}
      with_items:
        - virtualenv
        - flask
        - uwsgi
