---
  - name: Base web server installation/dependencies
    hosts: all
    remote_user: root

    roles:
      - web

  - name: UWSGI deployment and configuration
    hosts: all
    remote_user: ubuntu

    roles:
      - web
